// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/jinglanghe/go-start/internal/cache"
	"github.com/jinglanghe/go-start/internal/config"
	"github.com/jinglanghe/go-start/internal/database"
)

// Injectors from wire.go:

func Build() (*Application, func(), error) {
	appConfig := config.Init()
	db, cleanup := database.InitDb(appConfig)
	adapter, cleanup2 := cache.Init()
	application := &Application{
		Config: appConfig,
		Db:     db,
		Cache:  adapter,
	}
	return application, func() {
		cleanup2()
		cleanup()
	}, nil
}
