// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/jinglanghe/go-start/internal/config"
)

// Injectors from wire.go:

func Build() (*Application, func(), error) {
	appConfig := config.Init()
	application := &Application{
		Config: appConfig,
	}
	return application, func() {
	}, nil
}
